import type { Agent } from "@/lib/types";

export const agents: Agent[] = [
  {
    name: "KARMA",
    role: "Task intake and intent routing",
    status: "idle",
    current_task: "No active intake",
    last_activity: "Captured diligence workspace task",
    health: "healthy",
  },
  {
    name: "KOSH",
    role: "Knowledge retrieval",
    status: "active",
    current_task: "Validate hiring plan assumptions",
    last_activity: "Detected conflicting runway memory",
    health: "degraded",
  },
  {
    name: "SMRITI",
    role: "Memory ledger coordination",
    status: "idle",
    current_task: "Memory review queue",
    last_activity: "Marked renewal style as candidate memory",
    health: "healthy",
  },
  {
    name: "PRAGYA",
    role: "Planning and reasoning",
    status: "idle",
    current_task: "No active plan",
    last_activity: "Prepared diligence package plan",
    health: "healthy",
  },
  {
    name: "MURPHY",
    role: "Risk and failure analysis",
    status: "active",
    current_task: "Summarize product telemetry anomalies",
    last_activity: "Reviewing aggregate telemetry risk",
    health: "healthy",
  },
  {
    name: "MARYADA",
    role: "Policy and approval gate",
    status: "active",
    current_task: "Prepare investor diligence workspace",
    last_activity: "Requested Founder approval",
    health: "healthy",
  },
  {
    name: "RACHIT",
    role: "Delivery orchestration",
    status: "idle",
    current_task: "Awaiting approved work",
    last_activity: "Delivered renewal briefing",
    health: "healthy",
  },
  {
    name: "NIYANTRA",
    role: "Control plane coordination",
    status: "idle",
    current_task: "Workflow supervision",
    last_activity: "Updated active workflow counters",
    health: "healthy",
  },
  {
    name: "LISA",
    role: "Interface and notification layer",
    status: "failed",
    current_task: "Notification digest",
    last_activity: "Digest generation paused",
    health: "offline",
  },
];